name: Security сommons CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      confirm_action:
        description: "Type 'yes' if you want to publish and create a new tag"
        required: true
        default: "no"

env:
  MAVEN_CLI_OPTS: "-s etc/ci_settings.xml -Dmaven.repo.local=${{ github.workspace }}/.m2/repository"
  MAVEN_PUSH_USER: ${{ vars.MAVEN_PUSH_USER}}
  MAVEN_PUSH_TOKEN: ${{ secrets.MAVEN_PUSH_TOKEN }}
  NVD_API_TOKEN: ${{ secrets.NVD_API }}
  OSS_INDEX_USER: ${{ secrets.OSS_INDEX_USER }}
  OSS_INDEX_TOKEN: ${{ secrets.OSS_INDEX_TOKEN }}

jobs:
  get_current_version:
    uses: cyberrangecz/actions-templates/.github/workflows/get_version.yml@master
    with:
      file_path: "pom.xml"

  build_maven:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          cache: 'maven'

      - name: Cache NVD
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.m2/repository/org/owasp/dependency-check-data
          key: check-nvd-stable
          restore-keys: |
            check-nvd-stable

      - name: Build with Maven
        run: |
          mvn -ntp clean install $MAVEN_CLI_OPTS

  deploy_maven:
    needs: [build_maven, get_current_version]
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          cache: 'maven'

      - name: Get the short SHA
        if: github.ref != 'refs/heads/master'
        id: short_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set dev version
        if: github.ref != 'refs/heads/master'
        env:
          DEV_VERSION: ${{ format('{0}-dev-{1}', needs.get_current_version.outputs.version, steps.short_sha.outputs.sha_short) }}
        run: |
          mvn -ntp versions:set -DnewVersion="${DEV_VERSION}"

      - name: Deploy with Maven
        run: |
          mvn -ntp clean deploy -DskipTests -DskipChecks=true $MAVEN_CLI_OPTS

  # Controls if version consistent with server and higher than last git tag.
  control_tag:
    if: github.event.pull_request.base.ref == 'master' || github.ref == 'refs/heads/master'
    needs: get_current_version
    uses: cyberrangecz/actions-templates/.github/workflows/tag_control_template.yml@master
    with:
      VERSION: ${{ needs.get_current_version.outputs.version }}

  # Push tag only from manual workflow_dispatch with confirmed tag creation
  push_tag:
    needs: [ get_current_version, control_tag, deploy_maven ]
    uses: cyberrangecz/actions-templates/.github/workflows/tag_push_template.yml@master
    with:
      VERSION: ${{ needs.get_current_version.outputs.version }}
